Revert "Fixed `error C3861: 'Lv': identifier not found` This diagnostic occurred in the compiler generated function 'glm::vec<1,T,Q> &glm::vec<1,T,Q>::operator |=(const glm::vec<1,A,Q> &)'"
This reverts commit 1f7702d9b6cd2e17527cefab1e98154d789cbd71.